// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package p20160318.ice;

public interface Printer extends Ice.Object,
                                 _PrinterOperations, _PrinterOperationsNC
{
    public static final long serialVersionUID = 888368824L;
}
